name: llddm
channels:
  - open3d-admin
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - numpy=1.22.3
  - open3d=0.11.2
  - python=3.8.13
  - tensorflow=2.7.0
  - pip:
    - polyscope==1.3.1
    - pymeshlab==2022.2.post2
    - pyyaml==6.0